name: Terraform Provision and Deploy Sonarqube, PostgreSQL & Nginx

on:
 workflow_dispatch:
  inputs:
    type:
      description: 'Provision or destroy'
      required: true
      default: 'destroy'
      type: choice
      options:
        - provision
        - destroy

jobs:
  terraform-provision-resources:
    runs-on: ubuntu-latest
    if: ${{ inputs.type == 'provision' }} 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
    - name: Lint Terraform
      run: terraform fmt -recursive
    - name: Initialize Terraform
      run: terraform init
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    - name: Terraform Plan
      run: terraform plan
    - name: Terraform Apply
      run: terraform apply --auto-approve

  terraform-destroy-resources:
    runs-on: ubuntu-latest
    if: ${{ inputs.type == 'destroy' }} 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
    - name: Terraform Destroy
      run: terraform destroy --auto-approve
